server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    username: ${db.username.prod}
    password: ${db.password.prod}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_ecommerce
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect